name: Flutter Release

on:
  push:
    tags:
      - "v*"
    branches:
      - main

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: app
          submodules: recursive
          fetch-depth: 0

      - name: Decode Keystore
        if: runner.os == 'Linux'
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > /home/runner/work/tiefprompt/tiefprompt/release.keystore

      - name: Create key.properties
        if: runner.os == 'Linux'
        run: |
          cat <<EOF > app/android/key.properties
          storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=/home/runner/work/tiefprompt/tiefprompt/release.keystore
          EOF

      - name: Install dependencies
        run: |
          ./.flutter/bin/flutter doctor
          ./.flutter/bin/flutter pub get
        working-directory: app

      - name: Build APKs (Android)
        if: runner.os == 'Linux'
        run: ./.flutter/bin/flutter build apk --release --split-per-abi
        working-directory: app

      - name: Build App Bundle (Android)
        if: runner.os == 'Linux'
        run: ./.flutter/bin/flutter build appbundle --release
        working-directory: app

      - name: Build Linux App
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install \
            clang cmake git \
            ninja-build pkg-config \
            libgtk-3-dev liblzma-dev \
            libstdc++-12-dev
          ./.flutter/bin/flutter build linux
        working-directory: app

      - name: Build Windows App
        if: runner.os == 'Windows'
        run: ./.flutter/bin/flutter build windows
        working-directory: app

      - name: Package Windows Artifacts
        if: runner.os == 'Windows'
        run: |
          mkdir artifacts
          cp -recurse app/build/windows/x64/runner/Release/ artifacts/windows

      - name: Package Linux Artifacts
        if: runner.os == 'Linux'
        run: |
          mkdir -p artifacts
          if [ -d app/build/app/outputs/flutter-apk ]; then
            cp app/build/app/outputs/flutter-apk/*.apk artifacts/
          fi
          if [ -d app/build/app/outputs/bundle/release ]; then
            cp app/build/app/outputs/bundle/release/app-release.aab artifacts/
          fi
          if [ -d app/build/linux ]; then
            cp -r app/build/linux artifacts/linux
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tiefprompt-${{ runner.os }}
          path: artifacts/*

  fetch-and-release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          name: .*
          name_is_regexp: true
          path: artifacts/

      - name: Determine Pre-release Status
        id: prerelease_check
        run: |
          TAG_NAME="${{ github.ref_name }}"
          if [[ "$TAG_NAME" =~ ^v0\. || "$TAG_NAME" =~ - ]]; then
            echo "prerelease=true" >> $GITHUB_ENV
          else
            echo "prerelease=false" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: "Auto-generated Flutter release."
          draft: true
          prerelease: ${{ env.prerelease }}
          generate_release_notes: true
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

  nightly-release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          merge-multiple: true

      - name: Update Nightly GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly
          name: Nightly
          body: "Latest build from main branch."
          prerelease: true
          draft: false
          generate_release_notes: false
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
